### ISSUE TITLE
Header가 요소 뒤에 가려지는 문제

### ISSUE THREAD

**Issue by richcire** [SKKUD/skklub-v3-frontend#18]
<img width="1318" alt="스크린샷 2023-04-15 오후 3 43 56" src="https://user-images.githubusercontent.com/72065244/232192807-6f901130-7690-4e4f-a1ef-436d091cc742.png">

하위 컴포넌트에 position: relative 속성을 주면 header가 가려집니다.
header의 zIndex를 높게 설정해주면 해결될 수 도 있을거 같습니다.

**Comment by OHaEuN** [comment]
헉 그거 작업 중에 확인하고 zindex 높였어용 ~
완료되면 develop 브랜치에 머지하겠습니다~!
